config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # CRUD create, read, update, delete

  root 'welcome#index'

  # get 'articles', to: 'articles#index'
  # get 'articles/new', to: 'articles#new', as: 'new_article'
  # post 'articles', to: 'articles#create'
  # get 'articles/:id', to: 'articles#show', as: 'article'
  # get 'articles/:id/edit', to: 'articles#edit', as: 'edit_article'
  # patch 'articles/:id', to: 'articles#update'
  # delete 'articles/:id', to: 'articles#destroy'

  resources :articles do
    resources :comments
    resources :likes, only: %i[create destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 5}
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :users, through: :likes

  belongs_to :author, class_name: 'User'

  def tags=(value)
    value = sanitize_tags(value) if value.is_a?(String)
    super(value)
  end

  private
  
  def sanitize_tags(text)
    text.downcase.split.uniq
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :commenter, presence: true, email:true
  validates :body, presence: true, length: { in: 6..500 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :user, uniqueness: { scope: :article, message: 'User already liked'}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, foreign_key: :author_id
  has_many :likes
  has_many :liked_articles, through: :likes, source: :article
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :find_article, only: %i[show update edit destroy]
  before_action :authorize_article, only: %i[edit update destroy]
  
  def index
    @articles = Article.page(params[:page])

    if params[:q].present?
      @articles = @articles.where("? = any(tags)", params[:q].downcase)
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(permitted_attributes(Article))
    @article.author = current_user
    if @article.save
      flash[:notice] = 'Your article has been saved'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
    @comment = @article.comments.build(commenter: session[:commenter])
    @like = Like.find_or_initialize_by(article: @article, user: current_user)
  end

  def edit; end

  def update
    if @article.update(permitted_attributes(@article))
      flash[:notice] = 'Your article has been update'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = 'Your article has been deleted'
    redirect_to articles_path
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def authorize_article
    authorize @article
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @like = Like.find_or_initialize_by(article: @article, user: current_user)
    
    if @comment.save
      session[:commenter] = @comment.commenter
      flash[:notice] = 'Your comment has been saved'
      redirect_to article_path(@article)
    else
      render 'articles/show'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = 'Your comment has been deleted'
    redirect_to article_path(@comment.article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = Like.new(article_id: params[:article_id], user: current_user)
    like.save

    redirect_to article_path(like.article)
  end

  def destroy
    like = Like.find(params[:id])
    like.destroy

    redirect_to article_path(like.article)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', model: @article %>

<%= form_for @article do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, class: "form-control", placeholder: "Text" %>
  </div>
  <div class="form-group">
    <%= f.label :tags %>
    <%= f.text_field :tags, class: "form-control", placeholder: "Tags" %>
  </div>
  <p>
    <%= f.submit class: "btn btn-default" %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>List of articles</h1>

<%= form_tag articles_path, method: :get do %>
  <div class="input-group">
    <%= text_field_tag :q, params[:q] || "", class: "form-control" %>
    <span class="input-group-btn">
      <%= submit_tag "Search", class: "btn btn-default" %>
    </span>
  </div>
<% end %>

<h2><%= link_to "New article", new_article_path %></h2>
<table class="table">
    <thead>
      <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Text</th>
      <th>Author</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
  </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.id %></td>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= article.author.email %></td>
        <td>Comments: <%= article.comments.count %></td>
        <td><%= link_to "Show", article_path(article), class: "btn btn-info" %></td>
        <td>
          <% if policy(article).edit? %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-warning" %>
          <% end %>
          </td>
          <td>
            <% if policy(article).destroy? %>
              <%= link_to "Destroy", article_path(article), 
                  class: "btn btn-warning",
                  method: :delete,
                  data: { confirm: "Are you sure?"} %>
            <% end %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @articles %>

<h2><%= link_to "New article", new_article_path %></h2>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @article.title %>
</p>
<p>
	<strong>Text:</strong>
	<%= @article.text %>
</p>
<p>
	<strong>Author:</strong>
	<%= @article.author.email %>
</p>
<p>
	<strong>Tags:</strong>
	<% @article.tags.each do |tag| %>
		<%= link_to articles_path(q: tag), style: 'margin-left: 4px' do %>
			<span class="label label-info">
				<%= tag %>
		</span>
		<% end %>
	<% end %>
</p>
<p>
	<strong>Created at:</strong>
	<%= @article.created_at %>
</p>
<p>
	<strong>Updated at:</strong>
	<%= @article.updated_at %>
</p>

<%= pluralize(@article.likes.count,"person") %> liked this article

<% if @like.persisted? %>
	<span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
	<%= link_to "Unlike", article_like_path(@article, @like), method: :delete %>
<% else %>
	<span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
	<%= link_to "Like", article_likes_path(@article), method: :post %>
<% end %>

<%= render 'comments/form' %>

<h2>Comments</h2>

<%= render @article.comments.reload %>

<%= link_to "Back", articles_path %>
<% if @article.author == current_user %>
	<%= link_to "Edit", edit_article_path(@article) %>
<% end %>

app/views/comments/_comment.html.erb
<p>
	<strong>Commenter:</strong>
	<%= comment.commenter %>
</p>
<p>
	<strong>Body:</strong>
	<%= comment.body %>
</p>

<p>

<%= link_to "Destroy", article_comment_path(comment.article, comment),
      	method: :delete,
      	data: { confirm: "Are you sure?"} %>

      </p>

app/views/comments/_form.html.erb
<%= render 'shared/errors', model: @comment %>

<%= form_for([@article, @comment]) do |f| %>

  <div class="form-group">
    <%= f.label :commenter %>
    <%= f.text_field :commenter, class: "form-control", placeholder: "Commenter" %>
  </div>
	
	<div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control", placeholder: "Body" %>
  </div>

	<p>
		<%= f.submit class: "btn btn-default" %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if notice %>
      <div class="alert alert-info">
        <%= notice %>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger">
        <%= alert %>
      </div>
    <% end %>

    <% if current_user %>
      <p>
        Hello <%= current_user.email %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      </p>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path %>
      <%= link_to 'Sign up', new_user_registration_path %>
    <% end %>

    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if model.errors.any? %>
	<div class="alert alert-danger">
	  <h2>Errors!</h2>
	  <ul>
	    <% model.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	  </ul>
	</div>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>

<h1><%= link_to "My blog", articles_path %></h1>